-- Migration: Add TrangThai + LyDoHuy to HoaDon for Invoice Management
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HoaDon' AND COLUMN_NAME='TrangThai')
BEGIN
    ALTER TABLE HoaDon ADD TrangThai NVARCHAR(20) NOT NULL DEFAULT N'Thanh cong';
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='HoaDon' AND COLUMN_NAME='LyDoHuy')
BEGIN
    ALTER TABLE HoaDon ADD LyDoHuy NVARCHAR(500) NULL;
END
GO
